Models-sortie-event
Mettwasser/pyframe pull request #5
Opened 2023-06-09 16:38 UTC by Mettwasser

2023-06-09 16:40 UTC, Mettwasser reviewed
gud

2023-06-09 16:41 UTC, Mettwasser commented
Good, couldn't notice something faulty/wrong

2023-06-09 16:45 UTC, Mettwasser reviewed
Good, couldn't notice something faulty/wrong

2023-06-09 16:59 UTC, TobiTenno requested changes

2023-06-09 16:59 UTC, TobiTenno commented on warframe/worldstate/enums/faction.py
> +    Infestation = "Infestation"
Infested? not seen an infestation display in a while

2023-06-09 16:59 UTC, TobiTenno commented on warframe/worldstate/models/event.py
> +    "The time the Event started"
it's your code, but i don't love the members being completely unspaced with the docstrings...

2023-06-10 03:51 UTC, TobiTenno approved these changes

2023-06-10 03:51 UTC, merged